name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*
      - users/ericsciple/m162testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta

      # Basic checkout
      - name: Basic checkout
        id: foo
        uses: ./
        with:
          repository: actions/checkout
          ref: test-data/v2/basic
          path: basic

      - run: echo foo.outputs.bar is '${{ steps.foo.outputs.bar }}'
