name: Build and Test

on:
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: ${{ github.event.pull_request.head.sha }}
