name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        with:
          ref: ${{ github.event.after }}
