name: Build and Test

on:
  pull_request:
    branches:
    - master
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - env:
          GITHUB_JSON: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_JSON"
      - uses: actions/checkout@v2

