name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test-proxy:
    runs-on: ubuntu-latest
    container:
      image: alpine/git:latest
    services:
      squid-proxy:
        image: ubuntu/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://127.0.0.1:3128
    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      # Basic checkout using git
      - name: Checkout basic
        uses: ./
        with:
          ref: test-data/v2/basic
          path: basic
      - name: Verify basic
        run: __test__/verify-basic.sh

      # Basic checkout using REST API
      - name: Remove basic
        run: rm -rf basic
      - name: Override git version
        run: __test__/override-git-version.sh
      - name: Basic checkout using REST API
        uses: ./
        with:
          ref: test-data/v2/basic
          path: basic
      - name: Verify basic
        run: __test__/verify-basic.sh --archive
